### ISSUE TITLE
Trello client library local storage dependency

### ISSUE THREAD

**Issue by RobinClowers** [trello/api-docs#98] opened 2017-04-11 22:51 UTC
If a user has local storage disabled, they get errors and are forced to re-authorize every time they load the app. It would be good if there was a fallback strategy, maybe to cookies. At the least, it seems like local storage access should be wrapped in a try / catch.

**Comment by bentleycook** [comment] 2017-04-14 13:07
@RobinClowers Just to confirm, you are talking about the [Power-Ups Client Library](https://developers.trello.com/power-ups/client-library) and not [client.js](https://developers.trello.com/clientjs), right?

**Comment by RobinClowers** [comment] 2017-04-14 17:15
@bentleycook actually I was referring to client.js, but it looks like both scripts use localstorage outside a try / catch, so I think both could be improved.

**Comment by aaronjensen** [comment] 2017-04-17 20:39
@bentleycook fyi, Robin is on our team. I don't think this ended up being a blocker for us, but I think we see it in our error tracking on browsers w/o local storage. Also, it means that people w/o local storage have to reauthorize every session. Would it be better for us to store the token in user-specific power-up state? If so, we'd need a way to inject it into the trello client api (or we'd need to fork it)

**Comment by bentleycook** [comment] 2017-04-19 15:40
So I've put together two projects to try and reproduce this. The first is for client.js: https://all-the-auths.glitch.me/. You can check the code out for it [here](https://glitch.com/edit/#!/all-the-auths?path=views/index.html:17:39). I'm testing it without local storage enabled on Firefox. I'm able to authorize and then I _do_ have to re-authorize upon refresh, but that's expected. However, I'm *not* seeing any errors.

As for Power-Ups, I've put together a Power-Up that does nothing more than auth and deauthorize a user: https://glitch.com/edit/#!/authorizing-power-ups-example And I have it turned on for this board: https://trello.com/b/Y7MlsmhU/auth-test Playing around with it in Firefox, I don't see any errors.

Re-reading comments, it sounds like you're relying on client.js to grab/persist the token in the Power-Up. If that is the case, I'd recommend persisting in as this auth example Power-Up does. You should then be able to re-hydrate client.js with a token when the user refreshes the page.

**Comment by bentleycook** [comment] 2017-04-19 19:29
Thanks, was able to reproduce. Working on a fix now.

**Comment by bentleycook** [comment] 2017-04-27 15:14
We shipped a fix for this. Wrapped the localStorage code in a try/catch so that we don't throw errors if it is inaccessible because someone is in private mode nor if it is full.

**Closed by bentleycook** 2017-04-27 15:14 UTC
